#
# ESP32-C6 Super Mini board configuration
#
CONFIG_BOARD_SUPERMINI_C6=y
CONFIG_BOARD_LED_TYPE_RGB=y
CONFIG_BOARD_LED_GPIO=15
CONFIG_BOARD_LED_ACTIVE_LOW=n
CONFIG_BOARD_LED_IDLE_LEVEL=0
CONFIG_BOARD_LED_PULSE_US=25000
CONFIG_BOARD_HW_VERSION=0xC6
