#
# ESP32-C3 Super Mini board configuration
#
CONFIG_BOARD_SUPERMINI_C3=y
CONFIG_BOARD_LED_GPIO=8
CONFIG_BOARD_LED_ACTIVE_LOW=y
CONFIG_BOARD_LED_IDLE_LEVEL=1
CONFIG_BOARD_LED_PULSE_US=25000
CONFIG_BOARD_HW_VERSION=0xC3
